/***************************************************************
 * @author T. Odell
 * IB Computer Science
 ****************************************************************/

/***************************************************************
 * Price Calculator
 * 
 * This program is used to calculate the final price of an item.
 * It assumes a 10% discount and a 5% tax rate.
 * Neither of these are changeable in this version.
 * 
 * The purpose of this exercise is to practice building GUI and simple coding exercises.
 * 
 ***************************************************************/

/**************************************************************
*  Auto Generated Java Stuff is here
* This declares a Class called MainFrame (the name I gave the jFrame)
**************************************************************/
public class MainFrame extends javax.swing.JFrame {

    
     /***************************************************************
     * Here is the required Main code
     * This is all generated by Nebeans with the Swing editor
     * @param args the command line arguments
     ***************************************************************/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
        
        
    }    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();                               // The method initComponents is in the hidden part below
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        originalPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        discountPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        finalCost = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        butClear = new javax.swing.JButton();
        butExit = new javax.swing.JButton();
        butCalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PriceCalculator");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FINAL PRICE CALCULATOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("List Price");

        originalPrice.setText("The price tag");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("10% Discount");

        discount.setText("Good deal for you");
        discount.setFocusable(false);
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Discounted Price");

        discountPrice.setText("See how cheap?");
        discountPrice.setFocusable(false);
        discountPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountPriceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tax @ 5%");

        tax.setText("The Government's share");
        tax.setFocusable(false);
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("__________");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Final Cost");

        finalCost.setText("You Pay This");
        finalCost.setFocusable(false);
        finalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCostActionPerformed(evt);
            }
        });

        txtMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMessage.setText("Enter a List Price to Begin");
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMessage)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(originalPrice)
                                .addComponent(discount)
                                .addComponent(discountPrice)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tax, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(finalCost, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(originalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(discountPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        butClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butClear.setText("Clear");
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });

        butExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        butCalc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butCalc.setText("Calc");
        butCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(butCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butClear)
                .addGap(85, 85, 85)
                .addComponent(butExit)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butClear)
                    .addComponent(butExit)
                    .addComponent(butCalc))
                .addGap(41, 41, 41))
        );

        setSize(new java.awt.Dimension(500, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    

/*************************************************************
 * ***********************************************************
 * End of Auto Generated Stuff
 * Code to handle buttons and calculations follows
 * @param evt
 * ***********************************************************
 * ***********************************************************/    
    
    /* Method for Exit Button */
    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        System.exit (0);
    }//GEN-LAST:event_butExitActionPerformed

    /*************************************************************
     * Method for pressing the Calc button:
     * 1. Check for valid inputs using try and catch
     * 2. Convert from text to double
     * 3. Calculate discount, discounted price, tax, and final cost
     * *************************************************************/
    private void butCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcActionPerformed
        /**************************************
         * Declare variables here for clarity
         *************************************/
        double origPriceNum;                                            //number versions of buttons
        double discountVal;
        double discountPriceNum;
        double taxNum;
        double finalCostNum;
        
        try {                                                            // Executes try
            /*  Calculate the Numbers
            *   This is the onlyt place that is actual calculating code!
            */
            origPriceNum = Double.parseDouble(originalPrice.getText ());  // Convert from string to float
            discountVal = origPriceNum * .1;
            discountPriceNum = origPriceNum - discountVal;
            taxNum = discountPriceNum * .05;
            finalCostNum = discountPriceNum + taxNum;
            
            /* Display the numbers
            *  This is shockingly a pain!
            *  First, numbers must be coverted to string
            *  Then use the setText method to display them
            */
            String origPriceString = String.format ("%.2f", origPriceNum);          //Creates a string with 2 decimals
            String discountValString = String.format ("%.2f", discountVal);         //Creates a string with 2 decimals
            String discountPriceString = String.format ("%.2f", discountPriceNum);  //Creates a string with 2 decimals
            String taxString = String.format ("%.2f", taxNum);                      //Creates a string with 2 decimals
            String finalCostString = String.format ("%.2f", finalCostNum);          //Creates a string with 2 decimals
            
            /* Now display the results */
            originalPrice.setText (origPriceString);
            discount.setText (discountValString);
            discountPrice.setText (discountPriceString);
            tax.setText (taxString);
            finalCost.setText (finalCostString);
            
            
            
        } catch (NumberFormatException e) {                             // Exception handling for incorrect input
            txtMessage.setText("Must be a number");
        }
    }//GEN-LAST:event_butCalcActionPerformed
    
    /* Method for the Clear Button */
    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        originalPrice.setText("");
        discount.setText("");
        discountPrice.setText("");
        tax.setText("");
        finalCost.setText("");
        txtMessage.setText ("Please enter list price");
    }//GEN-LAST:event_butClearActionPerformed

    /**********************************************************
     * There are no actions for the other fields
     * Netbeans puts unused code here
     * *******************************************************/
    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void discountPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountPriceActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxActionPerformed

    private void finalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalCostActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

   
     /**************************************************************
     * More Netbeans/Swing generated stuff
     * Just leave it here and ignore it
     *************************************************************/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCalc;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butExit;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField discountPrice;
    private javax.swing.JTextField finalCost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField originalPrice;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
